---
- name: "This program for install the apache2 and wget package"
  hosts: all
  become: yes
  tasks:
    - name: "packages block"
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apache2
        - wget
        
